### ISSUE TITLE
Deploy to heroku and dbt run crashes

### ISSUE THREAD

**Issue by jrabbit** [whereat/whereat-location-server#3]
Heroku: https://gist.github.com/jrabbit/d1a1bbc68223adb7058a (heroku create -> git push)

Local: https://gist.github.com/jrabbit/09fc21fec861fcfc8fba

Maybe I missed a step?

**Comment by jrabbit** [comment]
Ok yeah looks like I didn't have all the env vars you need.

for reference that appears to be:

```
export WHEREAT_TEST_DATABASE_URL_1="postgres://postgres@localhost:5432/"
export WHEREAT_DEV_DATABASE_URL="postgres://postgres@localhost:5432/" 
export WHEREAT_TEST_DATABASE_URL_2="postgres://postgres@localhost:5432/"
export WHEREAT_PROD_DATABASE_URL="postgres://postgres@localhost:5432/"
export WHEREAT_ENVIRONMENT="DEVELOPMENT"
export WHEREAT_PKP_PUBLIC_KEY=""
export WHEREAT_PKP_BACKUP_KEY=""
export WHEREAT_PKP_EMERGENCY_KEY=""
export WHEREAT_PKP_REPORT_URI=""
export WHEREAT_PKP_MAX_AGE=""
```

**Comment by jrabbit** [comment]
After setting those I don't get a crash but it doesn't bind to the port? 

```
$http :5000

http: error: Request timed out (30s).
```

**Comment by aguestuser** [comment]
i'd try using the dockerized version of the environment at https://hub.docker.com/r/whereat/whereat-location-server/ ? then spinning up the server with `sbt run`

**Comment by aguestuser** [comment]
detailed instructions on running a local dev box with that setup can be found here: https://github.com/whereat/whereat-bash#to-install-a-docker-container-for-the-location-server

**Comment by aguestuser** [comment]
closing as addressed by existing documentation. feel free to re-open if that doesn't actually help you figure it out! :)
