### ISSUE TITLE
deploy w@-location-server via fat jar / docker file to eclips.is

### ISSUE THREAD

**Issue by aguestuser** [whereat/whereat-location-server#30]

**Comment by aguestuser** [comment]
note: PR [#28](https://github.com/whereat/whereat-location-server/pull/28) resolves this, but we still have some "brass tacks" stuff to figure out before actually deploying, pointing DNS record to new deploy.  @alxmrtn , @pnasrat -- keep notes on QA stuff we're trying to figure out here?

**Comment by pnasrat** [comment]
Do you want push on green to prod or a managed/version deploy process (eg weekly deploys at end of iteration). 

Also for production what do you want in terms of monitoring, alerting and who is responsible for outages, etc.

**Comment by alxmrtn** [comment]
Also, how are we going to talk to eclips.is programmatically?

**Comment by aguestuser** [comment]
@pnasrat : given we'll be working in spurts for the next little bit, i vote for push on green to prod. i don't have strong opinions about monitoring, but am happy to be point of contact for outages/alerts. perhaps we could also send any alerts to whereat.admin [at ] riseup [dot] net so that in the future a team with access to that account could do rotating "pager duty?"

@alxmrtn : talking to eclips.is seems sort of out of our hands until such point as they publish their API. for the time being, my vote is to build a deploy flow that works on AWS (go with what works!), but is as decoupled from the particularities of AWS as possible, then treat the problem of migrating to a different stack in a subsequent iteration. (with the proviso that we try to build the deploy process in a manner that is as vendor-independent as possible to reduce technical debt for an eventual migration.)

does that sound reasonable?

**Comment by aguestuser** [comment]
closing as duplicative of https://github.com/whereat/whereat-ci/issues/2
