### ISSUE TITLE
Key pinning and other high-level HTTP customizations should be run on like nginx

### ISSUE THREAD

**Issue by jrabbit** [whereat/whereat-location-server#4]
Having devs set PKP is really an insurmountable ask and I don't know how it would translate to docker.

**Comment by aguestuser** [comment]
sorry for not addressing this for so long! for dev box purposes, you can plug in just about any string you like for the PKP string and get the server code to run. for core maintainers wanting to use the actual values we have pinned, we can be reached on the contrib list whereat-contrib@riseup.net or our new gitter page: https://gitter.im/whereat/contrib

**Comment by aguestuser** [comment]
in any case, coupling the pinning to a particular server stack or deploy strategy (nginx, apache, etc...) is precisely what we were trying to avoid by including it in the application code. agree it's a bit inconvenient, but it contradicts some core design decisions of the project to flex on this issue. closing (for now) as out-of-scope. please feel free to re-open if the above stubbing strategy isn't workable or you'd like to collaborate on coming up with a better strategy. :)
